=== idragonb/eli/bkp 19-7-12/from web/Treebolic.dtd
<!-- DTD for treebolic v 1.8 20051227 -->

<!ELEMENT treebolic (tree,tools?)>
<!ATTLIST treebolic
	toolbar (true|false) #REQUIRED
	statusbar (true|false) #REQUIRED
	popupmenu (true|false) #IMPLIED
	tooltip (true|false) #IMPLIED
	focus-on-hover (true|false) #REQUIRED
	focus IDREF #IMPLIED
	xmoveto CDATA #IMPLIED
	ymoveto CDATA #IMPLIED
>

<!ELEMENT tree (img?,nodes,edges?)>
<!ATTLIST tree
	backcolor CDATA #IMPLIED
	forecolor CDATA #IMPLIED
	orientation CDATA #IMPLIED
	expansion CDATA #IMPLIED
	sweep CDATA #IMPLIED
	preserve-orientation (true|false) #IMPLIED
	fontface CDATA #IMPLIED
	fontsize CDATA #IMPLIED
	fontsizestep CDATA #IMPLIED
>

<!ELEMENT nodes (img?,default.treeedge?,node)>
<!ATTLIST nodes
	backcolor CDATA #IMPLIED
	forecolor CDATA #IMPLIED
>

<!ELEMENT node (label?,content?,treeedge?,img?,a?,mountpoint?,node*)>
<!ATTLIST node
	id ID #REQUIRED
	backcolor CDATA #IMPLIED
	forecolor CDATA #IMPLIED
>

<!ELEMENT label (#PCDATA)>

<!ELEMENT content (#PCDATA)>

<!ELEMENT a (#PCDATA)>
<!ATTLIST a
	href CDATA #REQUIRED
	target CDATA #IMPLIED
>

<!ELEMENT img (#PCDATA)>
<!ATTLIST img
	src CDATA #REQUIRED
>

<!ELEMENT mountpoint (a)>
<!ATTLIST mountpoint
	delaymount (true|false) #IMPLIED
	weight CDATA #IMPLIED
>

<!ELEMENT treeedge (label?,img?)>
<!ATTLIST treeedge
	color CDATA #IMPLIED
	stroke (solid|dot|dash) #IMPLIED
	toterminator (z|a|c|d|t|cf|df|tf) #IMPLIED
	fromterminator (z|a|c|d|t|cf|df|tf) #IMPLIED
	hidden (true|false) #IMPLIED
>

<!ELEMENT edges (default.edge?,edge*)>
<!ATTLIST edges
	hyperbolic (true|false) #IMPLIED
>

<!ELEMENT edge (label?,img?)>
<!ATTLIST edge
	from IDREF #REQUIRED
	to IDREF #REQUIRED
	color CDATA #IMPLIED
	stroke (solid|dot|dash) #IMPLIED
	toterminator (z|a|c|d|t|cf|df|tf) #IMPLIED
	fromterminator (z|a|c|d|t|cf|df|tf) #IMPLIED
	hidden (true|false) #IMPLIED
>

<!ELEMENT default.treeedge (img?)>
<!ATTLIST default.treeedge
	color CDATA #IMPLIED
	stroke (solid|dot|dash) #IMPLIED
	toterminator (z|a|c|d|t|cf|df|tf) #IMPLIED
	fromterminator (z|a|c|d|t|cf|df|tf) #IMPLIED
	hidden (true|false) #IMPLIED
>

<!ELEMENT default.edge (img?)>
<!ATTLIST default.edge
	color CDATA #IMPLIED
	stroke (solid|dot|dash) #IMPLIED
	toterminator (z|a|c|d|t|cf|df|tf) #IMPLIED
	fromterminator (z|a|c|d|t|cf|df|tf) #IMPLIED
	hidden (true|false) #IMPLIED
>

<!ELEMENT tools (menu?)>
<!ATTLIST tools
>

<!ELEMENT menu (menuitem*)>
<!ATTLIST menu
>

<!ELEMENT menuitem (label, a?)>
<!ATTLIST menuitem
	action (goto|search|focus) #REQUIRED
	match-target CDATA #IMPLIED
	match-scope (label|content|link|id) #IMPLIED
	match-mode (equals|startswith|includes) #IMPLIED
>

=== idragonb/eli/bkp 19-7-12/from web/test.xml
<?xml version="1.0" encoding="UTF-8"?><!--treebolic (c)Thu May 31 08:43:17 IDT 2012-->
<!DOCTYPE treebolic SYSTEM "Treebolic.dtd">
<treebolic toolbar="true" focus-on-hover="false" statusbar="false">
        <tree>
                <nodes>
                        <node id="root" backcolor="ff0000" forecolor="ffffff">
                                <label>Autocad</label>
                                <node id="X5323e0fbfb638ac8">
                                        <label>Concepts</label>
                                        <node id="X783813cf7165b151">
                                                <label>Database</label>
                                                <node id="X48d4bd106c034dba">
                                                        <label>Model</label>
                                                        <node id="Xd25a25dde6b15e56">
                                                                <label>Entities</label>
                                                                <node id="X9e581b524fad78de">
                                                                        <label>Simple</label>
                                                                        <node id="X7292f127f6538972" backcolor="66ffff">
                                                                                <label>Line</label>
                                                                        </node>
                                                                        <node id="Xffd20d1a0c138d67" backcolor="66ffff">
                                                                                <label>Arc</label>
                                                                        </node>
                                                                        <node id="X23c79998673cde29" backcolor="66ffff">
                                                                                <label>Ellipse</label>
                                                                        </node>
                                                                        <node id="X3734f589c39ace9d" backcolor="66ffff">
                                                                                <label>Point</label>
                                                                        </node>
                                                                </node>
                                                                <node id="X92e2f8cbf2a4eb99">
                                                                        <label>Different</label>
                                                                        <node id="X45d2be51112fe221">
                                                                                <label>Image</label>
                                                                        </node>
                                                                        <node id="Xcc74c6727092341b">
                                                                                <label>Ray</label>
                                                                        </node>
                                                                        <node id="Xd226adb15d57141a">
                                                                                <label>Xline</label>
                                                                        </node>
                                                                        <node id="Xdd98923e25bb0e14">
                                                                                <label>Trace</label>
                                                                        </node>
                                                                </node>
                                                                <node id="X9e089288abc58923">
                                                                        <label>Polyline-ish</label>
                                                                        <node id="X849f55e837c009e0" backcolor="66ffff">
                                                                                <label>LWPolyline</label>
                                                                        </node>
                                                                        <node id="X9bf0a14e64392032">
                                                                                <label>Mline</label>
                                                                        </node>
                                                                        <node id="Xfac2201be110a38">
                                                                                <label>Polyline</label>
                                                                        </node>
                                                                        <node id="Xc6913205cc444fc7">
                                                                                <label>Seqend</label>
                                                                        </node>
                                                                        <node id="X1513ebe50c20adf8">
                                                                                <label>Spline</label>
                                                                        </node>
                                                                        <node id="Xa337eba658cffbdf">
                                                                                <label>Vertex</label>
                                                                        </node>
                                                                </node>
                                                                <node id="Xd187135d021e083f">
                                                                        <label>Compound</label>
                                                                        <node id="Xf310296df85d7c87" backcolor="66ffff">
                                                                                <label>Insert</label>
                                                                        </node>
                                                                </node>
                                                                <node id="Xcbe57d3d2ced9024">
                                                                        <label>Dimension</label>
                                                                        <node id="X369cdb9fa72b2f3c" backcolor="66ffff">
                                                                                <label>Dimension</label>
                                                                        </node>
                                                                        <node id="Xd3266e0ce7f59d26">
                                                                                <label>Leader</label>
                                                                        </node>
                                                                        <node id="Xd113cd7bdd3e7d9d">
                                                                                <label>Tolerance</label>
                                                                        </node>
                                                                </node>
                                                                <node id="X7f3fb36ed6fb0dde">
                                                                        <label>Area designation</label>
                                                                        <node id="X9ab55d12da6f215f" backcolor="66ffff">
                                                                                <label>Hatch</label>
                                                                        </node>
                                                                        <node id="X7fa7239ce0fa67e2">
                                                                                <label>Region</label>
                                                                        </node>
                                                                        <node id="X702a0a7f30849a2a" backcolor="66ffff">
                                                                                <label>Solid</label>
                                                                        </node>
                                                                </node>
                                                                <node id="X3f5c94e2fbf758a0">
                                                                        <label>Text</label>
                                                                        <node id="Xfeade5a3368b8fdd">
                                                                                <label>Attdef</label>
                                                                        </node>
                                                                        <node id="X834261edf7248f16">
                                                                                <label>Attrib</label>
                                                                        </node>
                                                                        <node id="X706361a53fc4297">
                                                                                <label>Mtext</label>
                                                                        </node>
                                                                        <node id="Xe108b856ee2e6630">
                                                                                <label>Shape</label>
